version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "8080:15672"
            - "25676:25676"
    postgresql:
        image: postgres:latest
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test_db
        ports:
          - "5432:5432"

