"""alterando tabela de aplicacoes, inserindo a coluna IP

Revision ID: 2249531abbac
Revises: 04c67d3ef304
Create Date: 2023-05-02 11:17:45.310814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2249531abbac'
down_revision = '04c67d3ef304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('APPLICATIONS', sa.Column('ip', sa.String(), nullable=True, default='localhost'))
    op.drop_constraint('FUNCTIONALITIES_application_id_fkey', 'FUNCTIONALITIES', type_='foreignkey')
    op.create_foreign_key(None, 'FUNCTIONALITIES', 'APPLICATIONS', ['application_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('LOGS_functionality_id_fkey', 'LOGS', type_='foreignkey')
    op.create_foreign_key(None, 'LOGS', 'FUNCTIONALITIES', ['functionality_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('SOLICITATIONS_user_id_fkey', 'SOLICITATIONS', type_='foreignkey')
    op.create_foreign_key(None, 'SOLICITATIONS', 'USERS', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_unique_constraint(None, 'USERS', ['login'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USERS', schema='public', type_='unique')
    op.drop_constraint(None, 'SOLICITATIONS', schema='public', type_='foreignkey')
    op.create_foreign_key('SOLICITATIONS_user_id_fkey', 'SOLICITATIONS', 'USERS', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'LOGS', schema='public', type_='foreignkey')
    op.create_foreign_key('LOGS_functionality_id_fkey', 'LOGS', 'FUNCTIONALITIES', ['functionality_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'FUNCTIONALITIES', schema='public', type_='foreignkey')
    op.create_foreign_key('FUNCTIONALITIES_application_id_fkey', 'FUNCTIONALITIES', 'APPLICATIONS', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_column('APPLICATIONS', 'ip')
    # ### end Alembic commands ###
