"""add solicitation table

Revision ID: e63ffc696d24
Revises: 3c7db55d50a7
Create Date: 2023-04-24 16:56:59.881497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63ffc696d24'
down_revision = '3c7db55d50a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SOLICITATIONS',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint('FUNCTIONALITIES_application_id_fkey', 'FUNCTIONALITIES', type_='foreignkey')
    op.create_foreign_key(None, 'FUNCTIONALITIES', 'APPLICATIONS', ['application_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('LOGS_functionality_id_fkey', 'LOGS', type_='foreignkey')
    op.create_foreign_key(None, 'LOGS', 'FUNCTIONALITIES', ['functionality_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'LOGS', schema='public', type_='foreignkey')
    op.create_foreign_key('LOGS_functionality_id_fkey', 'LOGS', 'FUNCTIONALITIES', ['functionality_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'FUNCTIONALITIES', schema='public', type_='foreignkey')
    op.create_foreign_key('FUNCTIONALITIES_application_id_fkey', 'FUNCTIONALITIES', 'APPLICATIONS', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_table('SOLICITATIONS', schema='public')
    # ### end Alembic commands ###
